/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiSummarizeCallRouteImport } from './routes/api/summarize-call'
import { Route as ApiGenerateLeadsRouteImport } from './routes/api/generate-leads'
import { Route as ApiEnrichLeadRouteImport } from './routes/api/enrich-lead'
import { Route as ApiEnrichCandidateRouteImport } from './routes/api/enrich-candidate'
import { Route as ApiDailyBriefRouteImport } from './routes/api/daily-brief'
import { Route as ApiCallScriptRouteImport } from './routes/api/call-script'
import { Route as ApiAssistantExecuteRouteImport } from './routes/api/assistant-execute'
import { Route as ApiAssistantRouteImport } from './routes/api/assistant'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'

const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSummarizeCallRoute = ApiSummarizeCallRouteImport.update({
  id: '/api/summarize-call',
  path: '/api/summarize-call',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateLeadsRoute = ApiGenerateLeadsRouteImport.update({
  id: '/api/generate-leads',
  path: '/api/generate-leads',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEnrichLeadRoute = ApiEnrichLeadRouteImport.update({
  id: '/api/enrich-lead',
  path: '/api/enrich-lead',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEnrichCandidateRoute = ApiEnrichCandidateRouteImport.update({
  id: '/api/enrich-candidate',
  path: '/api/enrich-candidate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDailyBriefRoute = ApiDailyBriefRouteImport.update({
  id: '/api/daily-brief',
  path: '/api/daily-brief',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCallScriptRoute = ApiCallScriptRouteImport.update({
  id: '/api/call-script',
  path: '/api/call-script',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAssistantExecuteRoute = ApiAssistantExecuteRouteImport.update({
  id: '/api/assistant-execute',
  path: '/api/assistant-execute',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAssistantRoute = ApiAssistantRouteImport.update({
  id: '/api/assistant',
  path: '/api/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/api/assistant': typeof ApiAssistantRoute
  '/api/assistant-execute': typeof ApiAssistantExecuteRoute
  '/api/call-script': typeof ApiCallScriptRoute
  '/api/daily-brief': typeof ApiDailyBriefRoute
  '/api/enrich-candidate': typeof ApiEnrichCandidateRoute
  '/api/enrich-lead': typeof ApiEnrichLeadRoute
  '/api/generate-leads': typeof ApiGenerateLeadsRoute
  '/api/summarize-call': typeof ApiSummarizeCallRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/api/assistant': typeof ApiAssistantRoute
  '/api/assistant-execute': typeof ApiAssistantExecuteRoute
  '/api/call-script': typeof ApiCallScriptRoute
  '/api/daily-brief': typeof ApiDailyBriefRoute
  '/api/enrich-candidate': typeof ApiEnrichCandidateRoute
  '/api/enrich-lead': typeof ApiEnrichLeadRoute
  '/api/generate-leads': typeof ApiGenerateLeadsRoute
  '/api/summarize-call': typeof ApiSummarizeCallRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/api/assistant': typeof ApiAssistantRoute
  '/api/assistant-execute': typeof ApiAssistantExecuteRoute
  '/api/call-script': typeof ApiCallScriptRoute
  '/api/daily-brief': typeof ApiDailyBriefRoute
  '/api/enrich-candidate': typeof ApiEnrichCandidateRoute
  '/api/enrich-lead': typeof ApiEnrichLeadRoute
  '/api/generate-leads': typeof ApiGenerateLeadsRoute
  '/api/summarize-call': typeof ApiSummarizeCallRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/api/assistant'
    | '/api/assistant-execute'
    | '/api/call-script'
    | '/api/daily-brief'
    | '/api/enrich-candidate'
    | '/api/enrich-lead'
    | '/api/generate-leads'
    | '/api/summarize-call'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/api/assistant'
    | '/api/assistant-execute'
    | '/api/call-script'
    | '/api/daily-brief'
    | '/api/enrich-candidate'
    | '/api/enrich-lead'
    | '/api/generate-leads'
    | '/api/summarize-call'
    | '/.mcp/invoke-tool/$tool'
  id:
    | '__root__'
    | '/'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/api/assistant'
    | '/api/assistant-execute'
    | '/api/call-script'
    | '/api/daily-brief'
    | '/api/enrich-candidate'
    | '/api/enrich-lead'
    | '/api/generate-leads'
    | '/api/summarize-call'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  McpRoute: typeof McpRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  ApiAssistantRoute: typeof ApiAssistantRoute
  ApiAssistantExecuteRoute: typeof ApiAssistantExecuteRoute
  ApiCallScriptRoute: typeof ApiCallScriptRoute
  ApiDailyBriefRoute: typeof ApiDailyBriefRoute
  ApiEnrichCandidateRoute: typeof ApiEnrichCandidateRoute
  ApiEnrichLeadRoute: typeof ApiEnrichLeadRoute
  ApiGenerateLeadsRoute: typeof ApiGenerateLeadsRoute
  ApiSummarizeCallRoute: typeof ApiSummarizeCallRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/summarize-call': {
      id: '/api/summarize-call'
      path: '/api/summarize-call'
      fullPath: '/api/summarize-call'
      preLoaderRoute: typeof ApiSummarizeCallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-leads': {
      id: '/api/generate-leads'
      path: '/api/generate-leads'
      fullPath: '/api/generate-leads'
      preLoaderRoute: typeof ApiGenerateLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/enrich-lead': {
      id: '/api/enrich-lead'
      path: '/api/enrich-lead'
      fullPath: '/api/enrich-lead'
      preLoaderRoute: typeof ApiEnrichLeadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/enrich-candidate': {
      id: '/api/enrich-candidate'
      path: '/api/enrich-candidate'
      fullPath: '/api/enrich-candidate'
      preLoaderRoute: typeof ApiEnrichCandidateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/daily-brief': {
      id: '/api/daily-brief'
      path: '/api/daily-brief'
      fullPath: '/api/daily-brief'
      preLoaderRoute: typeof ApiDailyBriefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/call-script': {
      id: '/api/call-script'
      path: '/api/call-script'
      fullPath: '/api/call-script'
      preLoaderRoute: typeof ApiCallScriptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/assistant-execute': {
      id: '/api/assistant-execute'
      path: '/api/assistant-execute'
      fullPath: '/api/assistant-execute'
      preLoaderRoute: typeof ApiAssistantExecuteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/assistant': {
      id: '/api/assistant'
      path: '/api/assistant'
      fullPath: '/api/assistant'
      preLoaderRoute: typeof ApiAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  McpRoute: McpRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  ApiAssistantRoute: ApiAssistantRoute,
  ApiAssistantExecuteRoute: ApiAssistantExecuteRoute,
  ApiCallScriptRoute: ApiCallScriptRoute,
  ApiDailyBriefRoute: ApiDailyBriefRoute,
  ApiEnrichCandidateRoute: ApiEnrichCandidateRoute,
  ApiEnrichLeadRoute: ApiEnrichLeadRoute,
  ApiGenerateLeadsRoute: ApiGenerateLeadsRoute,
  ApiSummarizeCallRoute: ApiSummarizeCallRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
