/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiSummarizeCallRouteImport } from './routes/api/summarize-call'
import { Route as ApiGenerateLeadsRouteImport } from './routes/api/generate-leads'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSummarizeCallRoute = ApiSummarizeCallRouteImport.update({
  id: '/api/summarize-call',
  path: '/api/summarize-call',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateLeadsRoute = ApiGenerateLeadsRouteImport.update({
  id: '/api/generate-leads',
  path: '/api/generate-leads',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/generate-leads': typeof ApiGenerateLeadsRoute
  '/api/summarize-call': typeof ApiSummarizeCallRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/generate-leads': typeof ApiGenerateLeadsRoute
  '/api/summarize-call': typeof ApiSummarizeCallRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/generate-leads': typeof ApiGenerateLeadsRoute
  '/api/summarize-call': typeof ApiSummarizeCallRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/generate-leads' | '/api/summarize-call'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/generate-leads' | '/api/summarize-call'
  id: '__root__' | '/' | '/api/generate-leads' | '/api/summarize-call'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiGenerateLeadsRoute: typeof ApiGenerateLeadsRoute
  ApiSummarizeCallRoute: typeof ApiSummarizeCallRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/summarize-call': {
      id: '/api/summarize-call'
      path: '/api/summarize-call'
      fullPath: '/api/summarize-call'
      preLoaderRoute: typeof ApiSummarizeCallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-leads': {
      id: '/api/generate-leads'
      path: '/api/generate-leads'
      fullPath: '/api/generate-leads'
      preLoaderRoute: typeof ApiGenerateLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiGenerateLeadsRoute: ApiGenerateLeadsRoute,
  ApiSummarizeCallRoute: ApiSummarizeCallRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
